version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Europe/Moscow
    ports:
       - "5432:5432"
