# Generated by Django 3.2.7 on 2022-01-04 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220104_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.author'),
        ),
    ]
