# Generated by Django 3.2.7 on 2022-01-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_author_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('WG', 'Without genre'), ('BL', 'Business literature'), ('DT', 'Detectives and Thrillers'), ('NF', 'Nonfiction'), ('DR', 'Dramaturgy'), ('SE', 'Science and Education')], default='WG', max_length=2),
        ),
    ]
