# Generated by Django 3.2.7 on 2022-01-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('WG', 'Without genre'), ('BL', 'Business literature'), ('DT', 'Detectives and Thrillers'), ('NF', 'Nonfiction'), ('DR', 'Dramaturgy'), ('SE', 'Science and Education')], db_index=True, default='WG', max_length=2),
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128, verbose_name='Book title')),
                ('books', models.ManyToManyField(to='core.Book')),
            ],
        ),
    ]
