# Generated by Django 3.2.7 on 2022-01-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_book_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='title',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Catalog title'),
        ),
    ]
